version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"

  nicoscraper:
    image: jyhemark/nicoscrape:latest
    restart: always
    environment:
      POSTGRES_CONNECTION_STRING: "User ID=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Host=db;Port=5432;"
      ASPNETCORE_HTTP_PORTS: "80"
    ports:
      - "5000:80"